## Imports

In [2]:
! pip install transformers datasets matplotlib

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.6/8.6 MB 72.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.9/4.9 MB 117.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 167.4 MB/s eta 0:00:00


In [69]:
from datasets import load_from_disk
from transformers import AutoTokenizer
import torch
import matplotlib.pyplot as plt
tokenizer = AutoTokenizer.from_pretrained("EleutherAI/pythia-410m")

## All Datasets - Overview

In [70]:
import os
from datasets import load_from_disk

# Replace this with the path to your base directory containing dataset directories.
base_dir = "data"
count = 1
# Iterate over every item in the base directory.
peek = []
targets = ['','', '', 'feature_name', 'distribution','class_ids','contains_digit|probe_classes','class_ids', 'class','class','class','class','class']
for dataset_name in os.listdir(base_dir):
    dataset_path = os.path.join(base_dir, dataset_name)
    # Check if the item is a directory.
    if os.path.isdir(dataset_path):
        try:
            # Load the dataset from the directory.
            ds = load_from_disk(dataset_path)
            print(f"{count}) Dataset: {dataset_name}, Length: {len(ds)}")
            #a = set()
            #if targets[count]:
            #    for p in ds:
            #        a.add(p[targets[count]])
            #print('Classes:', a)
            print('Data Peek:', ds[0].keys())
            print('_'*25)
            count += 1
            peek.append(ds)
            # Iterate over the splits (e.g., train, test, validation) and print their lengths.
            #for split, split_dataset in ds.items():
            #    print(f"  {split} split length: {len(split_dataset)}")
        except Exception as e:
            print(f"Error loading dataset from '{dataset_path}': {e}")


Error loading dataset from 'data/modelscope': Directory data/modelscope is neither a `Dataset` directory nor a `DatasetDict` directory.
1) Dataset: ewt.pyth.512.-1, Length: 1438
Data Peek: dict_keys(['Number', 'Mood', 'Tense', 'VerbForm', 'PronType', 'Person', 'NumType', 'Voice', 'Gender', 'eos', 'first_eos', 'upos', 'dep', 'head', 'within_compound_token_ix', 'max_compound_token_ix', 'tokens', 'doc_id', 'split', 'position', 'upos_NOUN|probe_indices', 'upos_NOUN|probe_classes', 'upos_PUNC|probe_indices', 'upos_PUNC|probe_classes', 'upos_ADP|probe_indices', 'upos_ADP|probe_classes', 'upos_NUM|probe_indices', 'upos_NUM|probe_classes', 'upos_SYM|probe_indices', 'upos_SYM|probe_classes', 'upos_SCONJ|probe_indices', 'upos_SCONJ|probe_classes', 'upos_ADJ|probe_indices', 'upos_ADJ|probe_classes', 'upos_DET|probe_indices', 'upos_DET|probe_classes', 'upos_CCONJ|probe_indices', 'upos_CCONJ|probe_classes', 'upos_PROPN|probe_indices', 'upos_PROPN|probe_classes', 'upos_PRON|probe_indices', 'upos_PRO

## Wikipedia Sex Dataset

In [3]:
data = peek[9]
print('Length of dataset', len(data))
unique_count = {}
unique_keys = set()
for d in data:
    unique_count[d['class']] = unique_count.get(d['class'], 0) + 1
    unique_keys.update(d.keys())

Length of dataset 6000


In [4]:
print(unique_count)
print(unique_keys)

{'female': 3000, 'male': 3000}
{'surname_index_end', 'tokens', 'text', 'class', 'name_index_start', 'name_index_end', 'surname_index_start', 'name'}


In [10]:
sample = data[9]

name_range = list(range(sample['name_index_start'],sample['name_index_end']+1))
print('Name Tokens',name_range)
print(sample)
print('_'*25)
print(sample['tokens'][name_range])
print('_'*25)
print(f"|{tokenizer.decode(sample['tokens'][name_range])}|")
print('_'*25)
print(sample['class'])
#print(sample['text'][name_range])

Name Tokens [126, 127]
{'tokens': tensor([    0,    15,  5131,  3159,    14,  9188,    84,   651,   320,  7088,
         4661,   254,    13, 17215,    13,   285, 15541,    15,   187,   187,
          510,  7015, 18177,   273,   667,  1677, 17502,   310,  1900,   253,
         5968,   344, 10316,   281,   253,  8310,   273,  8801,   414,   285,
        13375,  1128,   783, 12315,   562,   273,   534,   344,  8203, 13436,
          521,  5705,    15,  1737,  2238,   273,  2660,   285,   752,  2408,
          273,  6009,  1304,   841,  1841,    32,  5863,   281,   849,  3332,
          247,  3522,   310,   253,  4498,  4824,    32,  1737,   253,  6500,
           13,   285,  2714,  7393,  1632,   273,   253, 16057,  1128,  5371,
          521,   246, 18909,   273, 35633,    32,   380,  1390,  1318,   273,
        21518,  3890,   398,    13,  2469,   285,  1246,  1128, 45924, 27119,
          296,   248,  5298,    13,  1608,  8765, 44929,  1128,   263,   275,
          776,  1211,  1388, 1

## Wikipedia Political Party

In [11]:
data = peek[10]
print('Length of dataset', len(data))
unique_count = {}
unique_keys = set()
for d in data:
    unique_count[d['class']] = unique_count.get(d['class'], 0) + 1
    unique_keys.update(d.keys())

Length of dataset 3000


In [12]:
print(unique_count)
print(unique_keys)

{'Democratic Party': 1500, 'Republican Party': 1500}
{'surname_index_end', 'tokens', 'text', 'class', 'name_index_start', 'name_index_end', 'surname_index_start', 'name'}


In [16]:
sample = data[10]

name_range = list(range(sample['name_index_start'],sample['name_index_end']+1))
print('Name Tokens',name_range)
print(sample)
print('_'*25)
print(sample['tokens'][name_range])
print('_'*25)
print(f"|{tokenizer.decode(sample['tokens'][name_range])}|")
print('_'*25)
print(f"|{sample['class']}|")
#print(sample['text'][name_range])

Name Tokens [122, 123, 124, 125, 126, 127]
{'tokens': tensor([    0,  2717,   281,  6215,   562,    13,   387,  1878,   281,   253,
         6070,   326,   352,   651,  1056,   352, 32811,   281,  2075,   253,
         4815,    15,   187,   187,     3, 33832, 14761,  1320,   273, 40459,
          285, 38042, 10260, 35479,  1110, 13120, 16936,   285,  4934,  4815,
         1698,    15, 13480, 29488,   858,   417,  4763,  2208,  8385,   846,
          253,  2137,    15,   496,   958,    13,   247,  2137,    14,  2606,
         1458,     6,  2507,   885,  2891,   327, 14997,  5486,   281, 43162,
        46044, 21731,  6194,  4288,  6376,   275,  1055,    13,  7562,  4195,
          373,  2169,   685,  3309,   449,   187,   187,    42,  1353, 29985,
          326, 16612,  1346,   323, 39995,    13,  1125,   375,    13,  4166,
           13,   285, 26429,   778,   452,   574,   247,  1133,   275,   352,
           15,   187,   187,  4576,  1311,  2300,  3489,    48,  1905,  2091,
        21

## Wikipedia Athlete

In [17]:
data = peek[11]
print('Length of dataset', len(data))
unique_count = {}
unique_keys = set()
for d in data:
    unique_count[d['class']] = unique_count.get(d['class'], 0) + 1
    unique_keys.update(d.keys())

Length of dataset 5000


In [18]:
print(unique_count)
print(unique_keys)

{'association football player': 1000, 'basketball player': 1000, 'baseball player': 1000, 'American football player': 1000, 'ice hockey player': 1000}
{'surname_index_end', 'tokens', 'text', 'class', 'name_index_start', 'name_index_end', 'surname_index_start', 'name'}


In [22]:
sample = data[2540]

name_range = list(range(sample['name_index_start'],sample['name_index_end']+1))
print('Name Tokens',name_range)
print(sample)
print('_'*25)
print(sample['tokens'][name_range])
print('_'*25)
print(f"|{tokenizer.decode(sample['tokens'][name_range])}|")
print('_'*25)
print(sample['class'])
#print(sample['text'][name_range])

Name Tokens [126, 127]
{'tokens': tensor([    0,  2626,   285, 13268, 30416,   267, 11691,   337,    27,  2504,
         1996,   281,  1918,  9756,   697,  7002,  4951,  3330,    15, 12705,
        15858,   438,   706,   249,  1160,  3307, 26866,   275,   253, 10170,
           15,   187,   187,  3848, 18415,  5602,    44, 32560,   285,   416,
           15,    43,    15,   530,  2480,  1063,  1097, 11691,   323,   253,
        10063,  5332,  1507,    13,   665,  8231,   616,  1273,  4951,   846,
         2876,   272,  2366,   271,  4314,    14, 13197, 29642,    15, 35176,
           74,  8679, 18540, 13456,  4136,   512,  1264,  7342,   327,  4791,
        13768,   275,   253,   873,  2135,    15,   187,   187,     3,  1231,
         3534,   598,  1264,  7342,   275,  1679,   685,   495,  2909,    15,
         1198,  8988,  2909,    13,   309,  1869,   359,  7303,   352,  3965,
          973,    15,  9240,  1264,  2909,    13,   326,   434,   253,  2165,
          937, 10063,  5332,  

## Alive

In [54]:
data = peek[7]
print('Length of dataset', len(data))
unique_count = {}
unique_keys = set()
for d in data:
    unique_count[d['class']] = unique_count.get(d['class'], 0) + 1
    unique_keys.update(d.keys())

print(unique_count)
print(unique_keys)

Length of dataset 6000
{'true': 3000, 'false': 3000}
{'surname_index_end', 'tokens', 'text', 'class', 'name_index_start', 'name_index_end', 'surname_index_start', 'name'}


In [55]:
sample = data[0]

name_range = list(range(sample['name_index_start'],sample['name_index_end']+1))
print('Name Tokens',name_range)
print(sample)
print('_'*25)
print(sample['tokens'][name_range])
print('_'*25)
print(f"|{tokenizer.decode(sample['tokens'][name_range])}|")
print('_'*25)
print(sample['class'])
#print(sample['text'][name_range])

Name Tokens [35, 36, 37]
{'tokens': tensor([    0,    46, 46929,   556, 26582, 31734,    15,  2053,   513,   417,
         4833, 21977,  2600,    13,  2167,   353, 46929,   778,  6233, 36662,
          323,  3580,  9716,  3066, 26582,  4859,    15,   187,   187, 13117,
        17416,  1511, 11412,   187,   187, 40616,   443, 12727,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,

In [59]:
1 if sample['class'] == 'true' else 0

1

## Occupation

In [62]:
data = peek[8]
print('Length of dataset', len(data))
unique_count = {}
unique_keys = set()
for d in data:
    unique_count[d['class']] = unique_count.get(d['class'], 0) + 1
    unique_keys.update(d.keys())

print(unique_count)
print(unique_keys)

Length of dataset 5980
{'singer': 1000, 'actor': 1000, 'politician': 1000, 'journalist': 1000, 'athlete': 1000, 'researcher': 980}
{'surname_index_end', 'tokens', 'text', 'class', 'name_index_start', 'name_index_end', 'surname_index_start', 'name'}


In [67]:
sample = data[2000]

name_range = list(range(sample['name_index_start'],sample['name_index_end']+1))
print('Name Tokens',name_range)
print(sample)
print('_'*25)
print(sample['tokens'][name_range])
print('_'*25)
print(f"|{tokenizer.decode(sample['tokens'][name_range])}|")
print('_'*25)
print(f"|{sample['class']}|")
#print(sample['text'][name_range])

Name Tokens [126, 127]
{'tokens': tensor([    0,   745,   342,   253, 14511,    15, 17814,   310,  1024, 13644,
        29075,  3006,   670,   849, 16922, 21088,  7902,   457,    84,  7185,
          285,   611,  1279,    70,  4255,   457,    84,   773,  4924,  1869,
          668,   588, 42620,  2806, 11163,   689,   281,   253,  8786,  7021,
           15,   535,   187,   688,   271,  1121,    14,   264,   323,   253,
        17372,  7648,  5687, 18879,    13,   773, 16008,  3778,  1680,   411,
         3288,   272,  5418,   657,   302,   398,   285, 43779,   253,  9922,
         7021,  1806, 33614,  2955,   282, 32920, 12013,    27,   187,   187,
        16008,  3778,   310, 42547,   387,  1633,  1643,   952,  1869,  1896,
           15,   754,   310,  2970,   690,  2806,   952,   281,  7277,   779,
          281, 22306,  6729,    15,  6729,  1904,   457,    85,   755, 16922,
         7902,   562,   273, 12907,    15,  6729,  1904,   457,    85, 34030,
         5332,   544, 32336,  

In [68]:
sample['class'] == 'actor'

True

## Natural Language

In [28]:
data = peek[4]
print('Length of dataset', len(data))
unique_count = {}
unique_keys = set()
for d in data:
    unique_count[d['class_ids'].item()] = unique_count.get(d['class_ids'].item(), 0) + 1
    unique_keys.update(d.keys())

print(unique_count)
print(unique_keys)

Length of dataset 28084
{4: 3137, 9: 3097, 2: 3090, 1: 3102, 3: 3126, 7: 2967, 5: 3155, 8: 3110, 6: 3300}
{'tokens', 'lang', 'probe_indices', 'valid_indices', 'class_ids'}


In [46]:
sample = data[25621]

print('_'*25)
print('Tokens shape',sample['tokens'].shape)
print('Valid indices shape', sample['valid_indices'].shape)
print('_'*25)
print('Decoded tokens at valid indices :',tokenizer.decode(sample['tokens'][sample['valid_indices']]))
print('_'*25)
print('Tokens at probe index:',sample['tokens'][sample['probe_indices']])
print('Decoded tokens at probe index:')
for t in sample['tokens'][sample['probe_indices']]:
    print(f"|{tokenizer.decode(t)}|")
print('class index:',sample['class_ids'].item())

_________________________
Tokens shape torch.Size([512])
Valid indices shape torch.Size([510])
_________________________
Decoded tokens at valid indices : μβουλίου για λίγον καιρό. Στον περιορισμένο χρόνο που έχετε στη διάθεσή σας, δεν μπορείτε να επιτύχετε κάτι μεγάλο, παρ’ όλ’ αυτά μπορείτε να δώσετε κατευθύνσεις σε κάποια θέματα όπως η ενέργεια και η επικουρικότητα. Μπορείτε επίσης να κάνετε κάτι για τα οικονομικά. Σας παρακαλώ, όμως, μην αφήσετε να σας παραπλανήσουν εκείνοι που είναι ιστορικά αποδεδειγμένο πως δεν μπορούν να διαχειριστούν χρήματα. Μην πιστέψετε ότι με περισσότερα χρήματα μπορεί κανείς αυτόματα να επιτύχει καλύτερα πράγματα. Χρήματα άλλωστε υπάρχουν, έχουμε 112 δισ. ευρώ. Το θέμα είναι μόνο τι θα τα κάνουμε. Είπατε ο ίδιος, κύριε Καγκελάριε, ότι το σημαντικότερο είναι η ερώτηση. Είπατε ο ίδιος πως πρέπει να δημιουργηθεί εμπιστοσύνη. Κάντε το λοιπόν! Περάστε στην πράξη! Πείτε ποιος θα πάρει τι, ποιος θα πληρώσει τι, από τα χρήματα της Ευρώπης.
Πόσες οικονομικές ενισχ

In [6]:
sample['valid_indices']

tensor([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
         15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,
         29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
         57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,
         71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,
         85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,
         99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
        127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140,
        141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154,
        155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
        169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 1

In [7]:
#code to select probe indices + 50 random positions
sample['probe_indices']

tensor([135, 485])

In [23]:
pos = list(set(torch.randint(low=0, high=len(sample['tokens']), size=(55,)).tolist() + sample['probe_indices'].tolist()))
for t in sample['probe_indices']:
    assert t in pos, f"Probe index {t} not in positions"
len(pos)

57

In [17]:
485 in pos

True

## Text Features

In [10]:
data = peek[5]
print('Length of dataset', len(data))
unique_count = {}
unique_keys = set()
for d in data:
    #unique_count[d['is_not_ascii|probe_classes'].item()] = unique_count.get(d['is_not_ascii|probe_classes'].item(), 0) + 1
    unique_keys.update(d.keys())

print(unique_count)
print(unique_keys)

Length of dataset 10000
{}
{'leading_capital|probe_classes', 'all_capitals|probe_indices', 'contains_digit|probe_indices', 'is_not_alphanumeric|probe_indices', 'contains_all_whitespace|probe_classes', 'no_leading_space_and_loweralpha|probe_indices', 'all_tokens', 'contains_capital|probe_indices', 'is_not_alphanumeric|probe_classes', 'text', 'leading_capital|probe_indices', 'all_digits|probe_indices', 'tokens', 'meta', 'contains_whitespace|probe_indices', 'has_leading_space|probe_classes', 'is_not_ascii|probe_indices', 'contains_whitespace|probe_classes', 'contains_all_whitespace|probe_indices', 'no_leading_space_and_loweralpha|probe_classes', 'is_not_ascii|probe_classes', 'contains_digit|probe_classes', 'has_leading_space|probe_indices', 'contains_capital|probe_classes', 'all_capitals|probe_classes', 'all_digits|probe_classes'}


In [12]:
len(unique_keys) == len(data[0].keys())

True

In [24]:
data[89]

{'text': 'Pedro Henrique Botelho\n\nPedro Henrique Botelho (born April 4, 1987) is a Brazilian football player currently playing for FK Sūduva in Lithuania.\n\nHe previously played in one Russian Premier League match for FC Krylia Sovetov Samara during the 2007 season.\n\nReferences\n\nCategory:1987 births\nCategory:Living people\nCategory:Brazilian footballers\nCategory:Brazilian expatriate footballers\nCategory:Expatriate footballers in Lithuania\nCategory:FC Krylia Sovetov Samara players\nCategory:Expatriate footballers in Russia\nCategory:Russian Premier League players\nCategory:Expatriate footballers in Latvia\n\nCategory:Association football defenders',
 'meta': {'pile_set_name': 'Wikipedia (en)'},
 'all_tokens': tensor([49789,   287, 33294,  1452, 28469,   293,  1689,   187,   187, 49789,
           287, 33294,  1452, 28469,   293,  1689,   313,  6448,  4162,   577,
            13, 12034,    10,   310,   247, 24110,  5842,  4760,  4390,  4882,
           323, 46789,   322, 15248

In [44]:
sample = data[3265]

list(set(torch.concat([sample['contains_digit|probe_indices'],sample['all_digits|probe_indices'], sample['contains_capital|probe_indices'],
 sample['leading_capital|probe_indices'],sample['all_capitals|probe_indices'],sample['contains_whitespace|probe_indices'],
sample['has_leading_space|probe_indices'],sample['no_leading_space_and_loweralpha|probe_indices'],sample['contains_all_whitespace|probe_indices'],
 sample['is_not_alphanumeric|probe_indices'],sample['is_not_ascii|probe_indices']]).tolist()))

[112, 93]

In [19]:
tokenizer.decode(sample['all_tokens'])

'Roman Catholic Diocese of Tambacounda\n\nThe Roman Catholic Diocese of Tambacounda () is a diocese located in the city of Tambacounda in the Ecclesiastical province of Dakar in Senegal.\n\nHistory\n August 13, 1970: Established as Apostolic Prefecture of Tambacounda from the Diocese of Kaolack and Diocese of Saint-Louis du Sénégal\n April 17, 1989: Promoted as Diocese of Tambacounda\n\nSpecial churches\n The cathedral is Cathédrale Marie Reine de l’Univers in Tambacounda, which is located in the Medina Coura neighborhood of the town.\n\nLeadership\n Bishops of Tambacounda (Roman rite)\n Bishop Jean-Noël Diouf (since 1989.04.17)\n Prefects Apostolic of Tambacounda (Roman rite) \n Fr. Clément Cailleau, C.S.Sp. (1970.08.13 – 1986.04.24)\n\nSee also\nRoman Catholicism in Senegal\n\nReferences\n\nExternal links\n GCatholic.org\n Catholic Hierarchy \n\nCategory:Roman Catholic dioceses in Senegal\nCategory:Tambacounda\nCategory:Christian organizations established in 1970\nCategory:Roman Cath

## Data subset

In [71]:
data = peek[3]
print('Length of dataset', len(data))
unique_count = {}
unique_keys = set()
for d in data:
    unique_count[d['distribution']] = unique_count.get(d['distribution'], 0) + 1
    unique_keys.update(d.keys())

print(unique_count)
print(unique_keys)

Length of dataset 8413
{'wikipedia': 730, 'pubmed_abstracts': 69, 'stack_exchange': 869, 'github': 1068, 'arxiv': 1905, 'uspto': 1056, 'freelaw': 1560, 'hackernews': 696, 'enron': 460}
{'tokens', 'distribution', 'text', 'probe_indices', 'all_tokens', 'valid_indices', 'meta'}


In [72]:
sample = data[11]

print('Tokens',sample['tokens'].shape)
print(tokenizer.decode(sample['tokens']))
print('_'*25)
print('Valid Tokens',sample['valid_indices'].shape)
print(tokenizer.decode(sample['tokens'][sample['valid_indices']]))
print('_'*25)
print('Tokens to Probe',sample['probe_indices'].shape)
print(sample['probe_indices'])
print([tokenizer.decode(sample['tokens'][t]) for t in sample['probe_indices']])
print('_'*25)
print(sample['distribution'])

Tokens torch.Size([512])
<|endoftext|> in 2005. The group has recorded two albums and has received the Sona 9 award, organized by Television of Catalonia, Catalunya Radio and the magazine Enderrock (readers chose the group as the best direct folk of 2007).

Filmography
 Living Is Easy with Eyes Closed (2013), 
 VI premis Barcelona de cinema (2007)
IV premios Max de las artes escénicas (2001).2000-2001) Plays Fredrika Armfeldt in "A Little Night Music", by Stephen Sondheim and Hugh Wheeler. Dir. Mario Gas.
 (2004) Special Performance of "Monólogos de la vagina", by Eve Ensler.
 (2009) Special Performance of "La nit més clara", by Clara Peya and Amadeu Bergés.
 (2009) Plays Srta. Mon in "Groucho me enseñó su camiseta", by Manuel Vázquez Montalbán and Damià Barbany. Dir. Damià Barbany.
 (2009) Play: "En viu", by Anna Maleras.
 (2009) Tribute: "Homenaje a Manuel Gas". Dir. Mario Gas.
 (2010) Plays Magda in "Rock 'n' Roll", by Tom Stoppard. Dir. Àlex Rigola.
 (2010-2011) Plays Dama visitant

In [73]:
for i in range(50):
    sample = data[i]
    print(sample['distribution'])

wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia
wikipedia


## Compound Words

In [49]:
peek[2][0]

{'tokens': tensor([16200,   369,   625,  2779,   275,  1363,   342, 36192,   313,  1093,
          7147,   470, 10543,   268,   426,   470,    15,  2640,   481,  2091,
          4272,   715,  1029,    14]),
 'label': 'missing_second',
 'feature_name': 'high-school'}

In [50]:
data = peek[2]
print('Length of dataset', len(data))
unique_count = {}
unique_feature = {}
unique_keys = set()
for d in data:
    unique_count[d['label']] = unique_count.get(d['label'], 0) + 1
    unique_feature[d['feature_name']] = unique_feature.get(d['feature_name'], 0) + 1
    unique_keys.update(d.keys())

print(unique_count)
print(unique_feature)
print(unique_keys)

Length of dataset 167959
{'missing_second': 67200, 'bigram': 33559, 'missing_first': 67200}
{'high-school': 8000, 'living-room': 7959, 'social-security': 8000, 'credit-card': 8000, 'blood-pressure': 8000, 'prime-factors': 8000, 'social-media': 8000, 'gene-expression': 8000, 'control-group': 8000, 'magnetic-field': 8000, 'cell-lines': 8000, 'trial-court': 8000, 'second-derivative': 8000, 'north-america': 8000, 'human-rights': 8000, 'side-effects': 8000, 'public-health': 8000, 'federal-government': 8000, 'third-party': 8000, 'clinical-trials': 8000, 'mental-health': 8000}
{'feature_name', 'label', 'tokens'}


In [53]:
sample = data[9658]
print(tokenizer.decode(sample['tokens']))
print('_'*25)
print(sample['label'])
print('_'*25)
print(sample['feature_name'])
print('_'*25)
print(sample['tokens'])
print(sample['tokens'].shape)
print(list(range(len(sample['tokens']))))

 sweat from my brow. I couldn't believe I'd actually pulled it off. I'd fooled everyone in the room
_________________________
missing_first
_________________________
living-room
_________________________
tensor([17052,   432,   619,  6479,    15,   309,  4571,   626,  2868,   309,
         1871,  2686,  7320,   352,   745,    15,   309,  1871, 11213,   264,
         4130,   275,   253,  2316])
torch.Size([24])
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]


## Latex

In [72]:
data = peek[1]
print('Length of dataset', len(data))

unique_keys = set()
for d in data:
    unique_keys.update(d.keys())

print(unique_keys)

Length of dataset 4486
{'is_title|probe_indices', 'start_math|probe_classes', 'end_math|probe_classes', 'is_title|valid_indices', 'is_subscript|valid_indices', 'is_reference|valid_indices', 'start_math|probe_indices', 'is_display_math|probe_indices', 'is_superscript|probe_classes', 'is_display_math|valid_indices', 'start_math|valid_indices', 'is_abstract|valid_indices', 'is_math|valid_indices', 'end_math|valid_indices', 'is_math|probe_indices', 'is_math|probe_classes', 'is_frac|probe_indices', 'is_denominator|valid_indices', 'is_display_math|probe_classes', 'is_subscript|probe_classes', 'is_author|valid_indices', 'tokens', 'is_numerator|valid_indices', 'is_author|probe_classes', 'is_inline_math|valid_indices', 'end_math|probe_indices', 'is_superscript|probe_indices', 'is_frac|probe_classes', 'is_frac|valid_indices', 'is_title|probe_classes', 'is_abstract|probe_indices', 'is_reference|probe_classes', 'is_denominator|probe_classes', 'is_inline_math|probe_indices', 'is_subscript|probe_ind

In [73]:
sample = data[106]
print(tokenizer.decode(sample['tokens']))
print('_'*25)

<|endoftext|>---
abstract: 'In many real-world applications, e.g. recommendation systems, certain items appear much more frequently than other items. However, standard embedding methods—which form the basis of many ML algorithms—allocate the same dimension to all of the items. This leads to statistical and memory inefficiencies. In this work, we propose mixed dimension embedding layers in which the dimension of a particular embedding vector can depend on the frequency of the item. This approach drastically reduces the memory requirement for the embedding, while maintaining and sometimes improving the ML performance. We show that the proposed mixed dimension layers achieve a higher accuracy, while using 8$\times$ fewer parameters, for collaborative filtering on the MovieLens dataset. Also, they improve accuracy by 0.1% using half as many parameters or maintain baseline accuracy using 16$\times$ fewer parameters for click-through rate prediction task on the Criteo Kaggle dataset.'
author

In [74]:
len(unique_keys) == len(data[0].keys())

True

In [95]:
import re
sample = data[0]

print('Tokens:',sample['tokens'].shape)
print('_'*25)
c = 1
for k in unique_keys:
    if 'valid_indices' in k:
        pr_key = re.sub('valid_indices','probe_indices',k)
        if pr_key not in sample:
            pr_key = 'N/A'
        print(f"{c}) {k} <> {pr_key}")
        print('Valid Shape',sample[k].shape)
        print('Probe Shape',sample[pr_key].shape)
        #print(sample[k][sample[pr_key]])
        valid_tokens = sample['tokens'][sample[k]]
        print(valid_tokens)
        probe_tokens = sample['tokens'][sample[pr_key]]
        print(probe_tokens)
        print('_'*25)
        c+= 1

Tokens: torch.Size([1024])
_________________________
1) is_title|valid_indices <> is_title|probe_indices
Valid Shape torch.Size([1024])
Probe Shape torch.Size([5])
tensor([19013,  3836,   275,   308,  4063, 17827,    27, 19540, 26253,   980,
        24704])
tensor([32125,  4063, 19540, 24704,  7884])
_________________________
2) is_subscript|valid_indices <> is_subscript|probe_indices
Valid Shape torch.Size([1024])
Probe Shape torch.Size([2])
tensor([], dtype=torch.int64)
tensor([32125,  7884])
_________________________
3) is_reference|valid_indices <> is_reference|probe_indices
Valid Shape torch.Size([1024])
Probe Shape torch.Size([7])
tensor([   39,  4448,   348,    36, 12456,    28,  1214, 27415,  2610,   589,
         7857,    28,  1214, 10859,   360, 12844,  6755,    28,  1214,    39,
         4448,   348,  6755,    28,  1214,  9263,  4396,   280, 28205,  6961,
           28,  1214,    45,   266, 32567,  6961,    59, 11801,  9755,    28,
         1214, 23262,  7857,    28,  1214, 

In [96]:
for k in unique_keys:
    if 'probe_indices' in k:
        print(f"sample['{k}'],",end=' ')

sample['is_title|probe_indices'], sample['start_math|probe_indices'], sample['is_display_math|probe_indices'], sample['is_math|probe_indices'], sample['is_frac|probe_indices'], sample['end_math|probe_indices'], sample['is_superscript|probe_indices'], sample['is_abstract|probe_indices'], sample['is_inline_math|probe_indices'], sample['is_subscript|probe_indices'], sample['is_denominator|probe_indices'], sample['is_reference|probe_indices'], sample['is_author|probe_indices'], sample['is_numerator|probe_indices'], 

In [100]:
sample = data[0]

list(set(torch.cat([sample['is_title|probe_indices'], sample['start_math|probe_indices'], sample['is_display_math|probe_indices'], sample['is_math|probe_indices'], sample['is_frac|probe_indices'], sample['end_math|probe_indices'], sample['is_superscript|probe_indices'], sample['is_abstract|probe_indices'], sample['is_inline_math|probe_indices'], sample['is_subscript|probe_indices'], sample['is_denominator|probe_indices'], sample['is_reference|probe_indices'], sample['is_author|probe_indices'], sample['is_numerator|probe_indices']]).tolist()))

[128, 140, 44, 237, 175, 589, 49, 178, 339, 145, 181, 952, 252, 1022]

## EWT

In [101]:
data = peek[0]
print('Length of dataset', len(data))

unique_keys = set()
for d in data:
    unique_keys.update(d.keys())

print(unique_keys)

Length of dataset 1438
{'dep_root|probe_indices', 'Person_2|probe_classes', 'eos_True|probe_classes', 'Gender_Masc|probe_classes', 'upos_PROPN|probe_indices', 'NumType', 'upos_SCONJ|probe_classes', 'dep_ccomp|probe_classes', 'VerbForm_Ger|probe_indices', 'dep_obj|probe_classes', 'Mood_Imp|probe_indices', 'Mood', 'upos_VERB|probe_classes', 'Gender_Fem|probe_indices', 'Gender_Fem|probe_classes', 'dep_conj|probe_indices', 'PronType_Rel|probe_indices', 'upos_NUM|probe_classes', 'upos_DET|probe_classes', 'Person_3|probe_classes', 'Voice', 'doc_id', 'dep_advmod|probe_classes', 'dep_obj|probe_indices', 'VerbForm_Fin|probe_indices', 'dep_nsubj:pass|probe_indices', 'PronType', 'upos_SYM|probe_indices', 'upos_PUNC|probe_indices', 'dep_parataxis|probe_classes', 'PronType_Prs|probe_classes', 'VerbForm_Ger|probe_classes', 'PronType_Int|probe_indices', 'dep_parataxis|probe_indices', 'tokens', 'upos_ADJ|probe_indices', 'dep_nsubj|probe_classes', 'VerbForm_Inf|probe_classes', 'upos_SYM|probe_classes',

In [102]:
sample = data[0]
for k in unique_keys:
    if 'probe_indices' in k:
        print(f"sample['{k}'],",end=' ')

sample['dep_root|probe_indices'], sample['upos_PROPN|probe_indices'], sample['VerbForm_Ger|probe_indices'], sample['Mood_Imp|probe_indices'], sample['Gender_Fem|probe_indices'], sample['dep_conj|probe_indices'], sample['PronType_Rel|probe_indices'], sample['dep_obj|probe_indices'], sample['VerbForm_Fin|probe_indices'], sample['dep_nsubj:pass|probe_indices'], sample['upos_SYM|probe_indices'], sample['upos_PUNC|probe_indices'], sample['PronType_Int|probe_indices'], sample['dep_parataxis|probe_indices'], sample['upos_ADJ|probe_indices'], sample['Number_Plur|probe_indices'], sample['dep_advmod|probe_indices'], sample['dep_case|probe_indices'], sample['Tense_Past|probe_indices'], sample['dep_aux|probe_indices'], sample['PronType_Prs|probe_indices'], sample['Gender_Neut|probe_indices'], sample['first_eos_True|probe_indices'], sample['upos_AUX|probe_indices'], sample['Person_1|probe_indices'], sample['dep_flat|probe_indices'], sample['dep_advcl|probe_indices'], sample['NumType_Card|probe_indi

In [110]:
upos = []
dep = []
other = []
for i, k in enumerate(unique_keys):
    print(i+1,end=' ')
    if isinstance(sample[k], torch.Tensor):
        print(f'{k}:{sample[k].shape}')
    else:
        print(f'{k}:{sample[k]}')
    if 'upos' in k:
        upos.append(k)
    elif 'dep' in k:
        dep.append(k)
    else:
        other.append(k)

1 dep_root|probe_indices:torch.Size([40])
2 Person_2|probe_classes:torch.Size([27])
3 eos_True|probe_classes:torch.Size([40])
4 Gender_Masc|probe_classes:torch.Size([7])
5 upos_PROPN|probe_indices:torch.Size([56])
6 NumType:torch.Size([512])
7 upos_SCONJ|probe_classes:torch.Size([45])
8 dep_ccomp|probe_classes:torch.Size([42])
9 VerbForm_Ger|probe_indices:torch.Size([45])
10 dep_obj|probe_classes:torch.Size([40])
11 Mood_Imp|probe_indices:torch.Size([31])
12 Mood:torch.Size([512])
13 upos_VERB|probe_classes:torch.Size([40])
14 Gender_Fem|probe_indices:torch.Size([7])
15 Gender_Fem|probe_classes:torch.Size([7])
16 dep_conj|probe_indices:torch.Size([39])
17 PronType_Rel|probe_indices:torch.Size([47])
18 upos_NUM|probe_classes:torch.Size([38])
19 upos_DET|probe_classes:torch.Size([48])
20 Person_3|probe_classes:torch.Size([15])
21 Voice:torch.Size([512])
22 doc_id:weblog-juancole.com_juancole_20051126063000_ENG_20051126_063000
23 dep_advmod|probe_classes:torch.Size([39])
24 dep_obj|probe_

In [111]:
len(upos), len(dep), len(other)

(33, 59, 62)

In [118]:
sample['tokens'].shape

torch.Size([512])

In [112]:
upos

['upos_PROPN|probe_indices',
 'upos_SCONJ|probe_classes',
 'upos_VERB|probe_classes',
 'upos_NUM|probe_classes',
 'upos_DET|probe_classes',
 'upos_SYM|probe_indices',
 'upos_PUNC|probe_indices',
 'upos_ADJ|probe_indices',
 'upos_SYM|probe_classes',
 'upos_ADV|probe_classes',
 'upos_CCONJ|probe_classes',
 'upos_NOUN|probe_classes',
 'upos_PROPN|probe_classes',
 'upos_AUX|probe_indices',
 'upos_NUM|probe_indices',
 'upos_ADV|probe_indices',
 'upos_X|probe_classes',
 'upos',
 'upos_DET|probe_indices',
 'upos_VERB|probe_indices',
 'upos_ADP|probe_classes',
 'upos_ADJ|probe_classes',
 'upos_ADP|probe_indices',
 'upos_SCONJ|probe_indices',
 'upos_PUNC|probe_classes',
 'upos_X|probe_indices',
 'upos_PRON|probe_classes',
 'upos_INTJ|probe_classes',
 'upos_NOUN|probe_indices',
 'upos_INTJ|probe_indices',
 'upos_AUX|probe_classes',
 'upos_CCONJ|probe_indices',
 'upos_PRON|probe_indices']

In [113]:
dep

['dep_root|probe_indices',
 'dep_ccomp|probe_classes',
 'dep_obj|probe_classes',
 'dep_conj|probe_indices',
 'dep_advmod|probe_classes',
 'dep_obj|probe_indices',
 'dep_nsubj:pass|probe_indices',
 'dep_parataxis|probe_classes',
 'dep_parataxis|probe_indices',
 'dep_nsubj|probe_classes',
 'dep_advmod|probe_indices',
 'dep_case|probe_indices',
 'dep_acl|probe_classes',
 'dep_aux|probe_indices',
 'dep_xcomp|probe_classes',
 'dep_list|probe_classes',
 'dep_amod|probe_classes',
 'dep_root|probe_classes',
 'dep_nmod|probe_classes',
 'dep_flat|probe_indices',
 'dep_nummod|probe_classes',
 'dep_advcl|probe_indices',
 'dep_nmod:poss|probe_classes',
 'dep_aux|probe_classes',
 'dep_acl:relcl|probe_indices',
 'dep_acl:relcl|probe_classes',
 'dep_conj|probe_classes',
 'dep_cop|probe_classes',
 'dep_nmod|probe_indices',
 'dep_obl|probe_indices',
 'dep_xcomp|probe_indices',
 'dep_cc|probe_classes',
 'dep_aux:pass|probe_classes',
 'dep_case|probe_classes',
 'dep_det|probe_classes',
 'dep_mark|probe_cl

In [124]:
{o:sample[o].shape if isinstance(sample[o],torch.Tensor) else sample[o] for o in other}

{'Person_2|probe_classes': torch.Size([27]),
 'eos_True|probe_classes': torch.Size([40]),
 'Gender_Masc|probe_classes': torch.Size([7]),
 'NumType': torch.Size([512]),
 'VerbForm_Ger|probe_indices': torch.Size([45]),
 'Mood_Imp|probe_indices': torch.Size([31]),
 'Mood': torch.Size([512]),
 'Gender_Fem|probe_indices': torch.Size([7]),
 'Gender_Fem|probe_classes': torch.Size([7]),
 'PronType_Rel|probe_indices': torch.Size([47]),
 'Person_3|probe_classes': torch.Size([15]),
 'Voice': torch.Size([512]),
 'doc_id': 'weblog-juancole.com_juancole_20051126063000_ENG_20051126_063000',
 'VerbForm_Fin|probe_indices': torch.Size([45]),
 'PronType': torch.Size([512]),
 'PronType_Prs|probe_classes': torch.Size([53]),
 'VerbForm_Ger|probe_classes': torch.Size([45]),
 'PronType_Int|probe_indices': torch.Size([45]),
 'tokens': torch.Size([512]),
 'VerbForm_Inf|probe_classes': torch.Size([42]),
 'Number_Plur|probe_indices': torch.Size([65]),
 'Voice_Pass|probe_classes': torch.Size([35]),
 'Tense_Past|pr

In [132]:
tokenizer.decode(sample['tokens'])

"<|endoftext|> Al-Zaman : American forces killed Shaikh Abdullah al-Ani, the preacher at the mosque in the town of Qaim, near the Syrian border. [This killing of a respected cleric will be causing us trouble for years to come.] DPA: Iraqi authorities announced that they had busted up 3 terrorist cells operating in Baghdad. Two of them were being run by 2 officials of the Ministry of the Interior! The MoI in Iraq is equivalent to the US FBI, so this would be like having J. Edgar Hoover unwittingly employ at a high level members of the Weathermen bombers back in the 1960s. The third was being run by the head of an investment firm. You wonder if he was manipulating the market with his bombing targets. The cells were operating in the Ghazaliyah and al-Jihad districts of the capital. Although the announcement was probably made to show progress in identifying and breaking up terror cells, I don't find the news that the Baathists continue to penetrate the Iraqi government very hopeful. It rem

In [130]:
sample['eos_True|probe_classes']

tensor([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1, -1, -1, -1,
        -1, -1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1,  1, -1, -1,  1, -1, -1,
        -1, -1, -1, -1])

In [133]:
token_lens = [sample['tokens'].shape[0] for sample in data]

In [134]:
min(token_lens), max(token_lens), sum(token_lens) / len(token_lens)

(512, 512, 512.0)

In [135]:
for k in unique_keys:
    if k == 'tokens':
        continue
    if isinstance(sample[k], torch.Tensor) and len(sample[k]) == 512:
        print(k)

NumType
Mood
Voice
PronType
eos
within_compound_token_ix
Number
first_eos
position
upos
max_compound_token_ix
dep
Gender
head
Tense
Person
VerbForm


In [143]:
sample['NumType'], sample['NumType_Card|probe_indices']

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
         0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0

In [145]:
for k in unique_keys:
    if 'probe_indices' in k:
        print(f"sample['{k}'],", end=' ')

sample['dep_root|probe_indices'], sample['upos_PROPN|probe_indices'], sample['VerbForm_Ger|probe_indices'], sample['Mood_Imp|probe_indices'], sample['Gender_Fem|probe_indices'], sample['dep_conj|probe_indices'], sample['PronType_Rel|probe_indices'], sample['dep_obj|probe_indices'], sample['VerbForm_Fin|probe_indices'], sample['dep_nsubj:pass|probe_indices'], sample['upos_SYM|probe_indices'], sample['upos_PUNC|probe_indices'], sample['PronType_Int|probe_indices'], sample['dep_parataxis|probe_indices'], sample['upos_ADJ|probe_indices'], sample['Number_Plur|probe_indices'], sample['dep_advmod|probe_indices'], sample['dep_case|probe_indices'], sample['Tense_Past|probe_indices'], sample['dep_aux|probe_indices'], sample['PronType_Prs|probe_indices'], sample['Gender_Neut|probe_indices'], sample['first_eos_True|probe_indices'], sample['upos_AUX|probe_indices'], sample['Person_1|probe_indices'], sample['dep_flat|probe_indices'], sample['dep_advcl|probe_indices'], sample['NumType_Card|probe_indi

In [150]:
list(set(torch.cat([sample['dep_root|probe_indices'], sample['upos_PROPN|probe_indices'], sample['VerbForm_Ger|probe_indices'], sample['Mood_Imp|probe_indices'], sample['Gender_Fem|probe_indices'], sample['dep_conj|probe_indices'], sample['PronType_Rel|probe_indices'], sample['dep_obj|probe_indices'], sample['VerbForm_Fin|probe_indices'], sample['dep_nsubj:pass|probe_indices'], sample['upos_SYM|probe_indices'], sample['upos_PUNC|probe_indices'], sample['PronType_Int|probe_indices'], sample['dep_parataxis|probe_indices'], sample['upos_ADJ|probe_indices'], sample['Number_Plur|probe_indices'], sample['dep_advmod|probe_indices'], sample['dep_case|probe_indices'], sample['Tense_Past|probe_indices'], sample['dep_aux|probe_indices'], sample['PronType_Prs|probe_indices'], sample['Gender_Neut|probe_indices'], sample['first_eos_True|probe_indices'], sample['upos_AUX|probe_indices'], sample['Person_1|probe_indices'], sample['dep_flat|probe_indices'], sample['dep_advcl|probe_indices'], sample['NumType_Card|probe_indices'], sample['upos_NUM|probe_indices'], sample['upos_ADV|probe_indices'], sample['dep_acl:relcl|probe_indices'], sample['dep_nmod|probe_indices'], sample['upos_DET|probe_indices'], sample['VerbForm_Part|probe_indices'], sample['Voice_Pass|probe_indices'], sample['dep_obl|probe_indices'], sample['upos_VERB|probe_indices'], sample['dep_xcomp|probe_indices'], sample['PronType_Art|probe_indices'], sample['dep_nummod|probe_indices'], sample['upos_ADP|probe_indices'], sample['Person_2|probe_indices'], sample['upos_SCONJ|probe_indices'], sample['dep_det|probe_indices'], sample['PronType_Dem|probe_indices'], sample['dep_cc|probe_indices'], sample['dep_compound|probe_indices'], sample['upos_X|probe_indices'], sample['upos_NOUN|probe_indices'], sample['dep_appos|probe_indices'], sample['dep_cop|probe_indices'], sample['dep_list|probe_indices'], sample['upos_INTJ|probe_indices'], sample['upos_CCONJ|probe_indices'], sample['upos_PRON|probe_indices'], sample['dep_aux:pass|probe_indices'], sample['Person_3|probe_indices'], sample['dep_nsubj|probe_indices'], sample['eos_True|probe_indices'], sample['VerbForm_Inf|probe_indices'], sample['dep_acl|probe_indices'], sample['dep_mark|probe_indices'], sample['Gender_Masc|probe_indices'], sample['dep_amod|probe_indices'], sample['dep_ccomp|probe_indices'], sample['dep_punct|probe_indices'], sample['dep_nmod:poss|probe_indices']]).tolist()))

[8,
 11,
 12,
 14,
 15,
 17,
 18,
 19,
 23,
 26,
 27,
 28,
 30,
 32,
 33,
 34,
 35,
 38,
 40,
 43,
 44,
 45,
 46,
 50,
 51,
 52,
 57,
 58,
 59,
 60,
 61,
 62,
 64,
 65,
 67,
 70,
 71,
 73,
 74,
 75,
 76,
 78,
 80,
 81,
 84,
 86,
 87,
 88,
 89,
 92,
 94,
 95,
 96,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 112,
 113,
 115,
 116,
 119,
 121,
 122,
 125,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 135,
 138,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 151,
 154,
 155,
 157,
 158,
 159,
 160,
 166,
 170,
 171,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 181,
 183,
 185,
 186,
 188,
 193,
 194,
 196,
 197,
 201,
 202,
 204,
 206,
 208,
 209,
 211,
 212,
 213,
 214,
 215,
 216,
 219,
 221,
 222,
 224,
 225,
 227,
 229,
 234,
 237,
 238,
 240,
 241,
 243,
 244,
 247,
 248,
 250,
 252,
 253,
 254,
 257,
 258,
 259,
 260,
 265,
 267,
 268,
 271,
 272,
 273,
 276,
 279,
 280,
 281,
 282,
 283,
 286,
 287,
 288,
 290,
 291,
 292,
 295,
 297,
 298,
 299,
 300,
 302,
 303,
 305

## Dataset Select

In [9]:
data = peek[9]
len(data)

6000

In [10]:
data_sub = data.select(list(range(1000,1438)))

In [11]:
data_sub[0]

{'tokens': tensor([    0,   326,  6351,  3486,   949,   253, 35240,   789,   908,   281,
         17093,   731,    15,   187,   187,    34, 19718, 16222,   281,  1445,
           275,   399,   373,  3354,  3936,   441,   896,   247,  3213,   275,
           673,    13,   281,   253,  1107,   816,  1078,   285,   846,  3645,
          3660,   309,    13,   672,   253,  2846,   369,  1728,   281,   247,
          1387,   273, 10846,   665,  1925,  3746,  9362,  2652,  3090, 33144,
            13,   253, 15454,    15,  2596,   273,   616,  7342,   369,   281,
         16497,  1270,  5685,  1445,   273,   253,  2469,  1905,  1219,  3381,
         12914,   399,  3090,  6554,    13, 22838, 45374,   607,  1905,   715,
           253,  3448,   273,  1246,    15,   496,   253,  1232,    13,   597,
         14257, 23179, 18299,  1204,    15,   187,   187,   688,   253, 18471,
            84,    13,   597,   574,  2323,    28,   368,   755,   247,  3282,
           273,   436,   275, 41888, 45681

In [12]:
data[1000]

{'tokens': tensor([    0,   326,  6351,  3486,   949,   253, 35240,   789,   908,   281,
         17093,   731,    15,   187,   187,    34, 19718, 16222,   281,  1445,
           275,   399,   373,  3354,  3936,   441,   896,   247,  3213,   275,
           673,    13,   281,   253,  1107,   816,  1078,   285,   846,  3645,
          3660,   309,    13,   672,   253,  2846,   369,  1728,   281,   247,
          1387,   273, 10846,   665,  1925,  3746,  9362,  2652,  3090, 33144,
            13,   253, 15454,    15,  2596,   273,   616,  7342,   369,   281,
         16497,  1270,  5685,  1445,   273,   253,  2469,  1905,  1219,  3381,
         12914,   399,  3090,  6554,    13, 22838, 45374,   607,  1905,   715,
           253,  3448,   273,  1246,    15,   496,   253,  1232,    13,   597,
         14257, 23179, 18299,  1204,    15,   187,   187,   688,   253, 18471,
            84,    13,   597,   574,  2323,    28,   368,   755,   247,  3282,
           273,   436,   275, 41888, 45681

In [13]:
tokenizer.pad_token

In [14]:
tokenizer.eos_token

'<|endoftext|>'

## Sparsify Explore

In [3]:
from sparsify.sparsify import Sae

In [4]:
saes = Sae.load_many('EleutherAI/sae-pythia-410m-65k')

Fetching 49 files:   0%|          | 0/49 [00:00<?, ?it/s]

Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}


In [5]:
saes.keys()

dict_keys(['layers.0.mlp', 'layers.1.mlp', 'layers.2.mlp', 'layers.3.mlp', 'layers.4.mlp', 'layers.5.mlp', 'layers.6.mlp', 'layers.7.mlp', 'layers.8.mlp', 'layers.9.mlp', 'layers.10.mlp', 'layers.11.mlp', 'layers.12.mlp', 'layers.13.mlp', 'layers.14.mlp', 'layers.15.mlp', 'layers.16.mlp', 'layers.17.mlp', 'layers.18.mlp', 'layers.19.mlp', 'layers.20.mlp', 'layers.21.mlp', 'layers.22.mlp', 'layers.23.mlp'])

In [6]:
sae = Sae.load_from_hub("EleutherAI/sae-pythia-410m-65k", hookpoint="layers.22.mlp")

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

Dropping extra args {'signed': False}


In [7]:
sae = sae.to('cuda:0')

### Testing the expected tensor shape in the sae forward method. It is: (inputs, input_embedding) i.e. (batch, seq, embedding) must be reduced to (batch * seq, embedding) before passing through forward

In [15]:
a = torch.rand((16,18,1024), device='cuda:0')
b = a.view(-1,1024).clone()
b_op = sae.forward(b)
c = b_op.sae_out.view(16,-1,1024)
c.shape

torch.Size([16, 18, 1024])

In [16]:
all_results = []
for i in range(a.shape[1]):
    temp_a = a[:,i,:]
    #print('Temp A',temp_a.shape)
    all_results.append(sae.forward(temp_a).sae_out)

In [17]:
c_prime = torch.stack(all_results,dim=1)
c_prime.shape

torch.Size([16, 18, 1024])

In [18]:
torch.allclose(c, c_prime)

True

## Testing how (batch, seq, embedding) can be translated into (n, embedding) and back to the (batch, seq, embedding) to maintain position information

In [19]:
import einops

422

In [20]:
batch = 16

ip = torch.rand((batch, torch.randint(100,1000,size=(1,)).item(), 1024), device='cuda:0') # batch, sequence, embedding
print('IP shape', ip.shape)
ip_mod = einops.rearrange(ip, "b s e -> (b s) e")
print('IP_Mod shape', ip_mod.shape)
ip_prime = einops.rearrange(ip_mod, "(b s) e -> b s e", b = batch)
print('IP_Prime shape', ip_prime.shape)
print('IP == IP_Prime:', torch.allclose(ip_prime, ip))
print('_'*25)
with torch.no_grad():
    enc = sae.encode(ip_mod)
    print(f"Top Activations: {enc.top_acts.shape}, Top Activations Indices: {enc.top_indices.shape}")
    print("Top Indices:", enc.top_indices[0,:])
    print("Top Activations", enc.top_acts[0,:])
    print('_'*25)
    op_mod = sae.decode(*enc)
    print("OP_Mod Shape",op_mod.shape)
    op = einops.rearrange(ip_mod, "(b s) e -> b s e", b = 16)
    print("OP Shape", op.shape)

IP shape torch.Size([16, 557, 1024])
IP_Mod shape torch.Size([8912, 1024])
IP_Prime shape torch.Size([16, 557, 1024])
IP == IP_Prime: True
_________________________
Top Activations: torch.Size([8912, 32]), Top Activations Indices: torch.Size([8912, 32])
Top Indices: tensor([ 4353,  8129, 10690, 15770, 15923, 17287, 17367, 26211, 29227, 29277,
        32894, 33289, 33903, 36181, 37275, 38507, 38586, 39625, 42146, 42744,
        42775, 48749, 49437, 50523, 51627, 51760, 52517, 52868, 56322, 57425,
        58835, 28422], device='cuda:0')
tensor([ 8.5520,  4.3722, 10.2342,  5.5670,  5.0898,  4.8645,  6.0769,  4.6501,
         4.7437,  4.3074,  6.3670,  4.3509,  4.7134,  5.8097,  4.8363,  5.1812,
         4.0863,  4.1682,  6.6390,  5.7630,  6.7948,  4.7071,  4.0192,  4.0508,
         4.9415,  6.9674,  5.1510,  4.4646,  4.0666,  5.0733,  4.1196,  3.9472],
       device='cuda:0')
_________________________
OP_Mod Shape torch.Size([8912, 1024])
OP Shape torch.Size([16, 557, 1024])


(torch.Size([8192, 32]), torch.Size([8192, 32]))

tensor([  475,  2200,  3976,  4078,  5535,  5780,  6660,  6829,  9490,  9783,
        10334, 10656, 11203, 11358, 11713, 12433, 14352, 16603, 19383, 19867,
        20635, 21283, 24260, 24993, 28392, 28526, 30227, 30303, 30336, 31305,
        31800,  6613], device='cuda:0')

tensor([ 1.7005,  1.7695,  3.2423,  1.8509,  1.6629,  3.0474,  1.5182,  2.4735,
         1.5209,  1.5189,  2.2650,  1.4994,  3.5307,  1.6637,  1.5109, 11.0463,
         2.2309,  2.4835,  1.6456,  1.4765,  1.5123,  2.6469,  2.5875,  2.8152,
         1.5593,  1.5475,  1.8769,  4.3661,  1.5953,  1.6941,  2.3382,  1.4640],
       device='cuda:0', grad_fn=<SliceBackward0>)

torch.Size([8192, 768])

In [49]:
sae.decode?

Signature: sae.decode(top_acts: torch.Tensor, top_indices: torch.Tensor) -> torch.Tensor
Docstring: <no docstring>
File:      /home/mltrain/sparsify/sparsify/sparse_coder.py
Type:      method

In [86]:
dec = sae.forward(ip_mod)

Pre-acts torch.Size([8752, 32768])
Y torch.Size([8752, 768])
sae_out torch.Size([8752, 768])
E torch.Size([8752, 768])


In [109]:
sae.cfg.num_latents

32768

In [88]:
dec.sae_out.shape

torch.Size([8752, 768])

In [92]:
dec.latent_acts.shape

torch.Size([8752, 32])

In [93]:
dec.latent_indices.shape

torch.Size([8752, 32])

In [99]:
dense = torch.zeros(8752, 32768, device=dec.latent_acts.device, dtype=dec.latent_acts.dtype)

In [100]:
dense.shape

torch.Size([8752, 32768])

In [101]:
dense.scatter_(1, dec.latent_indices, dec.latent_acts)

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], device='cuda:0', dtype=torch.bfloat16,
       grad_fn=<ScatterBackward0>)

In [102]:
dense.shape

torch.Size([8752, 32768])

In [107]:
p_sum = (dense != 0).sum(dim=-1)
print(p_sum.shape)
p_sum.min(), p_sum.max()

torch.Size([8752])


(tensor(32, device='cuda:0'), tensor(32, device='cuda:0'))

In [1]:
from pythia_sae import SAE

In [2]:
sae_handle = SAE(device='cuda:0')
sae_handle.load_many("EleutherAI/sae-pythia-160m-32k", layers=[1,2,3])

Fetching 50 files:   0%|          | 0/50 [00:00<?, ?it/s]

Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}
Dropping extra args {'signed': False}


Layer 1 laoded
Layer 2 laoded
Layer 3 laoded


In [3]:
sae_handle.sae_layers[1]

SparseCoder(
  (encoder): Linear(in_features=768, out_features=32768, bias=True)
)

In [4]:
import torch
ip = torch.rand((16,512,768), device='cuda:0')
op, sae_latents = sae_handle.compute_activations(ip, layer=1)

Pre-acts torch.Size([8192, 32768])
Y torch.Size([8192, 768])
sae_out torch.Size([8192, 768])
E torch.Size([8192, 768])


In [5]:
op.shape

torch.Size([16, 512, 768])

In [8]:
sae_latents.shape

torch.Size([16, 512, 32768])

In [9]:
p_sum = (sae_latents != 0).sum(dim=-1)

In [12]:
p_sum.min(), p_sum.max()

(tensor(32, device='cuda:0'), tensor(32, device='cuda:0'))

In [13]:
pos_sample = sae_latents[0, [500,501],:]
pos_sample.shape

torch.Size([2, 32768])

In [14]:
mean = pos_sample.mean(dim=-1).cpu().tolist()

In [15]:
mean

[0.0081787109375, 0.007293701171875]

In [22]:
tokenizer.encode(tokenizer.eos_token)[0]

0

## Shuffle and Select

In [74]:
def shuffle_and_select(*lists, n):
    # Ensure there is at least one list
    if not lists:
        raise ValueError("At least one list must be provided.")

    # Check that all lists are of equal length
    list_length = len(lists[0])
    if any(len(lst) != list_length for lst in lists):
        raise ValueError("All lists must have the same length.")

    # Zip the lists together to form a list of tuples.
    combined = list(zip(*lists))
    
    # Shuffle the combined list in-place
    random.shuffle(combined)
    
    # Select the first n elements
    selected = combined[:n]
    
    # Unzip the selected tuples back into separate lists
    # If n is 0, zip(*selected) would raise an error, so we handle that case.
    if selected:
        result_lists = list(map(list, zip(*selected)))
    else:
        # Return empty lists if no elements are selected
        result_lists = [[] for _ in lists]
    
    return result_lists

In [79]:
import random
total = 8413
select_n = 5000

In [83]:
indices = list(range(total))
random.shuffle(indices)
indices = indices[:select_n]

In [84]:
len(indices), max(indices), min(indices)

(5000, 8411, 1)

In [ ]:
def shuffle_and_select(model_activations, sae_activations, targets, total, select_n):
    indices = list(range(total))[:select_n]
    random.shuffle(indices)
    for layer in model_activations.keys():
        model_activations[layer] = [model_activations[layer][i] for i in indices]
        sae_activations[layer] = [sae_activations[layer][i] for i in indices]
    
        